// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecjqrmduagsbdgjmtkmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjanFybWR1YWdzYmRnam10a21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3Mjg4ODcsImV4cCI6MjA2NjMwNDg4N30._j6HAiXUsQaw1iSPeszDW7iS2sXyu41rZ06xWuhnl4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);